version: "3.9"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:1.18.0
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb
    network_mode: host
  kafka:
    image: 'bitnami/kafka:2.8.1'
    container_name: kafka-local
    network_mode: host
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper-local
    network_mode: host
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
